const data = {
    status: "success",
    items: [
        {
            id: 1,
            title: "Xiaomi Poco M4 Pro 5G",
            price: 71.522,
            image: "https://lh3.googleusercontent.com/XN9N_1JSG8OdVaOW2HhZaBYT5zehEpCUqbb1fpGJyHiOAv7czDccPR_C3AiJNyTUD283hS1eZTscjt1lbsor7l-QoE3zVA8Jfe9N4bw8",
            category: "Xiaomi",
            cantidad: 1,
          },
          {
            id: 2,
            title: "Xiaomi Redmi 10",
            price: 67.759,
            image: "https://lh3.googleusercontent.com/6E4hMmJxESAk5uD5bGM3L7wfa3Pi4GarNDfd7n1Sc0IMmTK2z8lkzpKf7K5CiOp__jLI2XcPA3Z5Jzn9YdWtDrvqjZSNqtWao9hDlLs",
            category: "Xiaomi",
            cantidad: 1,
          },
          {
            id: 3,
            title: "Xiaomi Poco M3 Pro",
            price: 62.065,
            image: "https://lh3.googleusercontent.com/vykUPJzUHwo9TsZfbqTVSxfs5V-D8AJ65VaCZU7PmhaFLg2tV3MZsCAkWn5VQMeULzIWN-2KN1FPJCjIJQyt09JSn3Ui7kyo51TxGBfT",
            category: "Xiaomi",
            cantidad: 1,
          },
          {
            id: 4,
            title: "Xiaomi Mi 11 Lite",
            price: 98.168,
            image: "https://lh3.googleusercontent.com/GN3cZykt8i5GwmHb3CCKhl-qoz3B5_KnCk2ZJBfprpl7p3RTB-6Vi80YdQAT2eph-M9rIh_kvddsWOGplQKOIW99ci8NThDo-uotVZ5i",
            category: "Xiaomi",
            cantidad: 1,
          },
          {
            id: 5,
            title: "Xiaomi Poco F3",
            price: 99.082,
            image: "https://lh3.googleusercontent.com/YF830k7KZa1GTAsHIg_cYBkpB-kZUOnHjn2w6PrhEiUd37meJaaYZseO27ewxNGNnmDmYR4hi-Hc_iiBgSfZyndoX8TYOq6wu7QMRbgh",
            category: "Xiaomi",
            cantidad: 1,
          },
          {
            id: 6,
            title: "Xiaomi Mi Note 10 Lite",
            price: 105.252,
            image: "https://lh3.googleusercontent.com/E_LyalWowdg2nXUFpwBm3BYuY9FGYIZiu57BNIsw86Who1IMzXypyLSPTCxouBfBF6VqeIy9tcy7PAxAODFETl__A8Ht7grj1CfUgAGn",
            category: "Xiaomi",
            cantidad: 1,
          },
          {
            id: 7,
            title: "Samsung A50 128gb Outlet",
            price: 42.120 ,
            image: "https://mercadositio.com/img/Producto/84477f10-3316-b64d-6829-060d8bb41f28/Sin-titulo-1-621f7f9aaf68d-wp.webp",
            category: "Samsung",
            cantidad: 1,
          },
          {
            id: 8,
            title: "Samsung Galaxy A03S",
            price: 38.280,
            image: "https://mercadositio.com/img/Producto/1285/cbb028138406d2b5fea90cc401eb37b7-6206cca767a67-wp.webp",
            category: "Samsung",
            cantidad: 1,
          },
          {
            id: 9,
            title: "Samsung Galaxy A22 128GB",
            price: 52.346,
            image: "https://mercadositio.com/img/Producto/1167/8f648d4a80fa6efe90ecbfe28553e784-6206cc0b073c2-wp.webp",
            category: "Samsung",
            cantidad: 1,
          },
          {
            id: 10,
            title: "Samsung Galaxy A52 128GB",
            price: 75.936,
            image: "https://mercadositio.com/img/Producto/988/501bb3a0a906550cd8202fda9535e5cb-6206ca32725c9-wp.webp",
            category: "Samsung",
            cantidad: 1,
          },
          {
            id: 11,
            title: "Samsung Galaxy M12 128GB",
            price: 46.860,
            image: "https://mercadositio.com/img/Producto/1053/dd450880c6c3d953536abdabdbc6c799-6206cba2bde98-wp.webp",
            category: "Samsung",
            cantidad: 1,
          },
          {
            id: 12,
            title: "Samsung Galaxy A32 128GB",
            price: 60.031 ,
            image: "https://mercadositio.com/img/Producto/1010/dc2984f9cb3fe6e8d9a358ba5b4c0ff8-6206cb6d51236-wp.webp",
            category: "Samsung",
            cantidad: 1,
          },
          {
            id: 13,
            title: "JBL Vibe 200TWS True",
            price: 7.342 ,
            image: "https://m.media-amazon.com/images/I/51jjO9RDlsS._AC_SY355_.jpg",
            category: "Auriculares",
            cantidad: 1,
          },
          {
            id: 14,
            title: "Apple AirPods Pro",
            price: 10.342,
            image: "https://m.media-amazon.com/images/I/71zny7BTRlL._AC_SX342_.jpg",
            category: "Auriculares",
            cantidad: 1,
          },
          {
            id: 15,
            title: "Apple AirPods (3ª generación)",
            price: 17.342,
            image: "https://m.media-amazon.com/images/I/51cjBa-4UeL._AC_UY218_.jpg",
            category: "Auriculares",
            cantidad: 1,
          },
          {
            id: 16,
            title: "JBL Tune 710BT - Audífonos inalámbricos ",
            price: 15.232 ,
            image: "https://m.media-amazon.com/images/I/619zjivnmYS._AC_SY355_.jpg",
            category: "Auriculares",
            cantidad: 1,
          },
          {
            id: 17,
            title: "Audífonos Noot K11 plegable",
            price: 13.031 ,
            image: "https://m.media-amazon.com/images/I/717y3KwQ4nL._AC_SX410_SY308_.jpg",
            category: "Auriculares",
            cantidad: 1,
          },
          {
            id: 18,
            title: "RORSOU R10 - Auriculares",
            price: 10.031 ,
            image: "https://m.media-amazon.com/images/I/71V-lsrtfWL._AC_SX410_SY308_.jpg",
            category: "Auriculares",
            cantidad: 1,
          },
          {
            id: 19,
            title: "RORSOU R10 - Auriculares",
            price: 10.031 ,
            image: "https://images-na.ssl-images-amazon.com/images/I/51kyjYuOZhL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
            category: "Auriculares",
            cantidad: 1,
          },
          {
            id: 20,
            title: "RORSOU R10 - Auriculares",
            price: 10.031 ,
            image: "https://m.media-amazon.com/images/I/71y+Gb3N-hL._AC_SY355_.jpg",
            category: "Auriculares",
            cantidad: 1,
          },
          {
            id: 21,
            title: "RORSOU R10 - Auriculares",
            price: 10.031 ,
            image: "https://m.media-amazon.com/images/I/71zg+MRBmEL._AC_SY355_.jpg",
            category: "Auriculares",
            cantidad: 1,
          },
     ],
};

export default data;